### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by kathrinklee** [qbicsoftware/projectbrowser-portlet#6] opened 2019-02-22 15:44 UTC
Hi, I'm trying to compile the portlet, but receiving the following error:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< life.qbic:projectbrowser-portlet >------------------
[INFO] Building ProjectBrowser Portlet 1.7.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
Downloading from nexus-snapshots: https://qbic-repo.am10.uni-tuebingen.de/repository/maven-snapshots/life/qbic/portal-utils-lib/1.2.0-SNAPSHOT/maven-metadata.xml
Downloading from nexus-snapshots: https://qbic-repo.am10.uni-tuebingen.de/repository/maven-snapshots/life/qbic/portal-utils-lib/1.2.0-SNAPSHOT/portal-utils-lib-1.2.0-SNAPSHOT.pom
[WARNING] The POM for life.qbic:portal-utils-lib:jar:1.2.0-SNAPSHOT is missing, no dependency information available
Downloading from nexus-releases: https://qbic-repo.am10.uni-tuebingen.de/repository/maven-releases/junit/junit-dep/maven-metadata.xml
Downloading from nexus-snapshots: https://qbic-repo.am10.uni-tuebingen.de/repository/maven-snapshots/junit/junit-dep/maven-metadata.xml
Downloading from nexus-snapshots: https://qbic-repo.am10.uni-tuebingen.de/repository/maven-snapshots/life/qbic/portal-utils-lib/1.2.0-SNAPSHOT/portal-utils-lib-1.2.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.304 s
[INFO] Finished at: 2019-02-22T16:36:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project projectbrowser-portlet: Could not resolve dependencies for project life.qbic:projectbrowser-portlet:war:1.7.0-SNAPSHOT: Could not find artifact life.qbic:portal-utils-lib:jar:1.2.0-SNAPSHOT in nexus-snapshots (https://qbic-repo.am10.uni-tuebingen.de/repository/maven-snapshots) -> [Help 1]
```
Any idea what is going wrong here?
Best & thanks

**Comment by chahuistle** [comment] 2019-02-22 16:27
The problem is that the library `portal-utils-lib`, version `1.2.0-SNAPSHOT` does not exist because it already has been released as version `1.2.0`.

If you have a look at the `development` branch, you will see that this has already been fixed in the `pom.xml`. If you are not able to do this, you can manually change this in your copy of `pom.xml`.

**Closed by chahuistle** 2019-02-22 16:27 UTC
